/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CT4;

/**
 *
 * @author User
 */
public class CT4_practic extends javax.swing.JFrame {

    /**
     * Creates new form CT4_practice
     */
    public CT4_practic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Student = new javax.swing.JLabel();
        CT = new javax.swing.JLabel();
        Mid = new javax.swing.JLabel();
        Final = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CTmark = new javax.swing.JTextField();
        MIDmark = new javax.swing.JTextField();
        FINALmark = new javax.swing.JTextField();
        GradeCalculator = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtGrade = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Student.setText("Student ID");
        jPanel1.add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        CT.setText("    CT");
        jPanel1.add(CT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        Mid.setText("Mid");
        jPanel1.add(Mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        Final.setText("Final");
        jPanel1.add(Final, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 90, -1));
        jPanel1.add(CTmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 90, -1));

        MIDmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDmarkActionPerformed(evt);
            }
        });
        jPanel1.add(MIDmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 90, -1));

        FINALmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINALmarkActionPerformed(evt);
            }
        });
        jPanel1.add(FINALmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 90, -1));

        GradeCalculator.setText("Calculate Grade");
        GradeCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeCalculatorActionPerformed(evt);
            }
        });
        jPanel1.add(GradeCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 390, 290));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGrade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtGrade.setForeground(new java.awt.Color(153, 153, 255));
        txtGrade.setText("Grade");
        jPanel3.add(txtGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 60, 30));

        lbltotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltotal.setForeground(new java.awt.Color(255, 0, 0));
        lbltotal.setText("Total");
        jPanel3.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 90, 30));

        jLabel4.setText("Grade");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 60, 30));

        jLabel3.setText("Total Mark");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 350, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void MIDmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDmarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIDmarkActionPerformed

    private void FINALmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINALmarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FINALmarkActionPerformed

    private void GradeCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeCalculatorActionPerformed
        // TODO add your handling code here:
//        GradeInfo jf1= new GradeInfo();//objectfor SignUp for;
//        jf1.show();//display JFM2
//        dispose();//close after open JFM2
//        
        double CT,MID,FINAL,total = 0;
        String Grade;
        //CT = CTmark.getText();
        CT=Integer.parseInt(CTmark.getText());
        MID=Integer.parseInt(MIDmark.getText());
        FINAL=Integer.parseInt(FINALmark.getText());
        total=CT+MID+FINAL;
        
        if(total>=85)
        {
            Grade= "A";
        }
        else if(total>=75)
        {
            Grade="B";
        }
         else if(total>=65)
        {
            Grade="C";
        }
         else if(total>=55)
        {
            Grade="D";
        }
         else if(total>=45)
        {
            Grade="S";
        }
        else
         {
             Grade="F";
         }
        lbltotal.setText(String.valueOf(total));
        txtGrade.setText(Grade);
    }//GEN-LAST:event_GradeCalculatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CT4_practic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CT4_practic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CT4_practic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CT4_practic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CT4_practic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CT;
    private javax.swing.JTextField CTmark;
    private javax.swing.JTextField FINALmark;
    private javax.swing.JLabel Final;
    private javax.swing.JButton GradeCalculator;
    private javax.swing.JTextField MIDmark;
    private javax.swing.JLabel Mid;
    private javax.swing.JLabel Student;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JLabel txtGrade;
    // End of variables declaration//GEN-END:variables
}
